uint8 ID

float32 Range
	# m

float32 Speed
	# m/s

float32 Angle
	# deg

float32 Width
	# m
	
float32 Length
	# m
	

float32 Pos_x
	# m
	
float32 Pos_y
	# m

float32 Speed_x
	# m/s
	
float32 Speed_y
	# m/s


float32 ACC_x
	# m/s2

float32 ACC_y
	# m/s2

float32 ExistProb
	# 0~2.55
	
float32 SNR
	# dB


uint8   DynProp
	# 0.unknown
	# 1.coming
	# 2.leaving
	# 3.still


uint8 ObjMeasState
	# 0: not exist
	# 1: new
	# 2: measured
	# 3: predicted
	# 4: is going to disappear
